### ISSUE TITLE
Keepalive stops at CLOCK command timeout

### ISSUE THREAD

**Issue by maartenweyns** [OnFreund/pyrisco#11]
Currently, it looks like when the `CLOCK` command experiences a timeout, the `_keep_alive` task stops executing. This causes issues in the Home Assistant risco integration, as it requires a manual reload of the integration to make the alarm system responsive again.

I don't know why this happens. After all, the `_keep_alive` function is an async task and shouldn't stop executing because of an exception, right?

**Comment by OnFreund** [comment]
The keep alive task does handle timeouts ([they're caught and raised](https://github.com/OnFreund/pyrisco/blob/master/pyrisco/local/risco_socket.py#L106) as an `OperationError`, which is [caught, reported](https://github.com/OnFreund/pyrisco/blob/master/pyrisco/local/risco_socket.py#L85), and execution continues).

My guess is that the keep alive is timing out due to a lost connection, and that lost connection is causing other failures.
