### ISSUE TITLE
Increase retry number for cloud requests

### ISSUE THREAD

**Issue by seederp2p** [OnFreund/pyrisco#16]
Hi!

Based on these issues:

https://github.com/home-assistant/core/issues/94124
https://github.com/home-assistant/core/issues/99201

I assume that the integration uses "pyrisco". I'm not a dev but I can see some "retry" counts on pyrisco.

Would it be ok to increase that count so maybe we get a more stable integration on HA?

Thank you!

**Comment by OnFreund** [comment]
I'm not sure this is going to help, and if they are, it will probably come with a noticeable delay.
I'm willing to try though - can you change the retry count no your local instance and see if it helps?

**Comment by seederp2p** [comment]
> I'm not sure this is going to help, and if they are, it will probably come with a noticeable delay. I'm willing to try though - can you change the retry count no your local instance and see if it helps?

Hi! Thank you for the reply!

Sure!! Can you please guide me on what I've to change? I'm using HASSIO

**Comment by OnFreund** [comment]
You'll need to find your copy of PyRisco (location depends on your installation method), and change `NUM_RETRIES = 3` to a higher number

**Comment by swaptoo** [comment]
If i see the retry count, it is used for creating the async pipe from the script to Risco? then i do not think this will solve anything. because in the case for me there is a good connection. and we get a valid response from Risco. But i do not think that error 72 is a connection error, just an unknown status code that we think it is a connection error.
