### ISSUE TITLE
HA Integration - Communication delay not used in RiscoLocal setup

### ISSUE THREAD

**Issue by FredericMa** [OnFreund/pyrisco#27]
Hi,

I'm creating this issue in this repo and not in the HA repo to discuss a bit "offline".
I haven't used the integration for a while and I've recently moved over to definitely use the Risco integration instead of my previous setup. 
I noticed that it often takes a very long before HA establishes the connection to my alarm panel (>10 mins).
It times out and retries until it finally manages to connect.
While checking the code I noticed that the `communication_delay` parameter is not used anymore in the `_async_setup_local_entry` in `__init__.py`.

I do recall that part of the changes I made have been reverted in https://github.com/home-assistant/core/pull/113497 but I thought that only the update logic was removed. It appears that also the `communication_delay` parameter has been removed from the creation of the `RiscoLocal` instance.

Was this done intentionally or by mistake? Now it also doesn't really make sense to determine the comm delay in the config flow.

On the other hand I also don't really understand the comment of bdraco on the PR:
> The event loop shouldn't get blocked for more than 100ms in 2024.4.x during startup anymore from python imports (or hopefully anything else). Previous version had event loop blocks > 10s when importing large integrations

Does this mean that using the comm delay in the setup isn't allowed anymore?
I'm now using the integration as a custom component and changed the first lines of `_async_setup_local_entry` to:
```python
async def _async_setup_local_entry(hass: HomeAssistant, entry: ConfigEntry) -> bool:
    data = entry.data
    comm_delay = data.get(CONF_COMMUNICATION_DELAY, 0)
    concurrency = entry.options.get(CONF_CONCURRENCY, DEFAULT_CONCURRENCY)
    risco = RiscoLocal(
        data[CONF_HOST], data[CONF_PORT], data[CONF_PIN], communication_delay=comm_delay, concurrency=concurrency
    )
```

It works like a charm now.

**Comment by FredericMa** [comment]
Any feedback on this?

**Comment by pierrecdn** [comment]
Hi there, and @OnFreund,

Discovered this integration yesterday and I gave a try. Managed to make it work locally using pyrisco, with settings such as `communication_delay=1, concurrency=1`, but never in HA, most probably due to this.

Mine is an old one, Agility 3 series, so I need to have access to these parameters and it seems the revert in HA mentionned here entirely removed the ability to use them, in addition to the while True loop which was most probably the cause of the issue.

Any plan to reintroduce somehow?

**Comment by OnFreund** [comment]
I do intend to reintroduce this to HA, but it's going to take a while till I get around to it. You're welcome to do it as well, and I'll review.

Please continue the conversation [here](https://github.com/home-assistant/core/issues/130660), since PyRisco already has everything necessary to support this, it's the HA side that needs work.

**Comment by pierrecdn** [comment]
In the end, I managed to do the integration, it just takes a while to succeed, both on first addition and when HA restarts.
Not entirely sure that it is the root cause in the end, even though the trials with pyrisco were OK-ish.
